/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastrocriptohash.view;

import cadastrocriptohash.model.PessoaEntity;
import cadastrocriptohash.repository.PessoaRep;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victor
 */
public class BuscarPorCpf extends javax.swing.JFrame {

    /**
     * Creates new form BuscarPorNome
     */
    public BuscarPorCpf() {
        initComponents();
        addTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroCriptoPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("CadastroCriptoPU").createEntityManager();
        pessoaEntityQuery = java.beans.Beans.isDesignTime() ? null : CadastroCriptoPUEntityManager.createQuery("SELECT p FROM PessoaEntity p");
        pessoaEntityList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pessoaEntityQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        txtPesquisaCpf = new javax.swing.JTextField();
        btnPesquisaCpf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPessoa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busca CPF");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtPesquisaCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 13, 107, -1));

        btnPesquisaCpf.setText("Pesquisar Cpf");
        btnPesquisaCpf.setMaximumSize(new java.awt.Dimension(125, 23));
        btnPesquisaCpf.setMinimumSize(new java.awt.Dimension(125, 23));
        btnPesquisaCpf.setPreferredSize(new java.awt.Dimension(125, 23));
        btnPesquisaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCpfActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisaCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        tblPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPessoa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, 375, 275));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCpfActionPerformed
        DefaultTableModel model =(DefaultTableModel) tblPessoa.getModel();
        model.setRowCount(0);
        if (txtPesquisaCpf.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Insira um nome para Pesquisa");
        }else{
            addLinhaTabela();
        }
    }//GEN-LAST:event_btnPesquisaCpfActionPerformed
    public class tabelaPessoa{
            String nome;
            String cpf;
            String rg;
            String cep;

        public tabelaPessoa(String nome, String cpf, String rg, String cep) {
            this.nome = nome;
            this.cpf = cpf;
            this.rg = rg;
            this.cep = cep;
        }

                  
    }
    
    public ArrayList ListarPessoas(){
        
        PessoaRep pessoa = new PessoaRep();

        ArrayList<tabelaPessoa> lista = new ArrayList<>();
        
        ArrayList<PessoaEntity> listaPessoas = new PessoaRep().listarPorCPF(txtPesquisaCpf.getText());

            for (int i = 0; i < listaPessoas.size(); i++) {
                pessoa.setNome(listaPessoas.get(i).getNome());
                pessoa.setCpf(listaPessoas.get(i).getCpf());
                pessoa.setRg(listaPessoas.get(i).getRg());
                pessoa.setCep(listaPessoas.get(i).getCep());
            }
        tabelaPessoa tbpessoa = new tabelaPessoa(pessoa.getNome(), pessoa.getCpf(), pessoa.getRg(), pessoa.getCep());
        lista.add(tbpessoa);
        return lista;
    }
    private void addTabela(){
        DefaultTableModel model = new DefaultTableModel()
	{
		@Override
		public boolean isCellEditable(final int row, final int column) {
			return false;
		}
                
	};
        tblPessoa.setModel(model);
            model.addColumn("Nome");
            model.addColumn("Cpf");
            model.addColumn("Rg");
            model.addColumn("Cep");
           
    }
    
    public void addLinhaTabela(){
        DefaultTableModel model = (DefaultTableModel) tblPessoa.getModel();
        ArrayList<tabelaPessoa> lista = ListarPessoas();
        
        Object rowDaTa[] = new Object[6];
        for (int i = 0; i < lista.size(); i++) {
            rowDaTa[0] = lista.get(i).nome;
            rowDaTa[1] = lista.get(i).cpf;
            rowDaTa[2] = lista.get(i).rg;
            rowDaTa[3] = lista.get(i).cep;
            model.addRow(rowDaTa);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPorCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPorCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPorCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPorCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPorCpf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager CadastroCriptoPUEntityManager;
    private javax.swing.JButton btnPesquisaCpf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<cadastrocriptohash.model.PessoaEntity> pessoaEntityList;
    private javax.persistence.Query pessoaEntityQuery;
    private javax.swing.JTable tblPessoa;
    private javax.swing.JTextField txtPesquisaCpf;
    // End of variables declaration//GEN-END:variables
}
