/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastrocriptohash.view;


import cadastrocriptohash.model.UsuarioEntity;
import cadastrocriptohash.repository.UsuarioRep;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victor
 */
public class ListaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form listaUsuarios
     */
    public ListaUsuarios() {
        initComponents();
        addTabela();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        btnDeletar = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Usuarios");
        setMinimumSize(new java.awt.Dimension(443, 420));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios Cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 31, 375, 275));

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 319, -1, -1));

        txtID.setEditable(false);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 320, 20, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public class tabelaUsuario{
            Integer id;
            String login;
            String senha;

        public tabelaUsuario(Integer id, String login, String senha) {
            this.id = id;
            this.login = login;
            this.senha = senha;
        }                  
    }
    
    
    
    public ArrayList ListarUsuario(){
        
        UsuarioRep usuario = new UsuarioRep();

        ArrayList<tabelaUsuario> lista = new ArrayList<>();
        
        ArrayList<UsuarioEntity> listaUsuarios = new UsuarioRep().listar();

            for (int i = 0; i < listaUsuarios.size(); i++) {
                usuario.setId(listaUsuarios.get(i).getId());
                usuario.setLogin(listaUsuarios.get(i).getLogin());
                usuario.setSenha(listaUsuarios.get(i).getSenha());   
                tabelaUsuario tbusuario = new tabelaUsuario(usuario.getId(), usuario.getLogin(), usuario.getSenha());
                lista.add(tbusuario);
            }
        
        return lista;
    }
    
    private void addTabela(){
        DefaultTableModel model = new DefaultTableModel()
	{
		@Override
		public boolean isCellEditable(final int row, final int column) {
			return false;
		}
                
	};
        tblUsuario.setModel(model);
        
           
            model.addColumn("Id");
            model.addColumn("Login");
            model.addColumn("Senha");
            ArrayList<UsuarioEntity> listaUsuarios = new UsuarioRep().listar();

            addLinhaTabela();
            
        
        
    }
            
    public void addLinhaTabela(){
        
        DefaultTableModel model = (DefaultTableModel) tblUsuario.getModel();
        ArrayList<tabelaUsuario> lista = ListarUsuario();
        
        Object rowDaTa[] = new Object[3];
        for (int i = 0; i < lista.size(); i++) {
            rowDaTa[0] = lista.get(i).id;
            rowDaTa[1] = lista.get(i).login;
            rowDaTa[2] = lista.get(i).senha;
            
            model.addRow(rowDaTa);
        }
    }
    
    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        UsuarioRep usuRep = new UsuarioRep();
        usuRep.setId(Integer.valueOf(txtID.getText()));
        
        DefaultTableModel model = (DefaultTableModel) tblUsuario.getModel();
        model.removeRow(tblUsuario.getSelectedRow());
        
        usuRep.excluir(usuRep);
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
       txtID.setText(tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 0).toString());
       //Quando clicado na tabela, passa o valor da linha selecionada / coluna 1 (vetor 0) como id para a caixa de texto que em seguida seta como id para deletar!
    }//GEN-LAST:event_tblUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
