/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastrocriptohash.view;

/**
 *
 * @author victor
 */
public class Navegacao extends javax.swing.JFrame {

    /**
     * Creates new form Navegacao
     */
    public Navegacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadastro = new javax.swing.JMenuItem();
        menuAtualizar = new javax.swing.JMenuItem();
        menuDeletar = new javax.swing.JMenuItem();
        menuBusca = new javax.swing.JMenu();
        menuBuscaNome = new javax.swing.JMenuItem();
        menuBuscaCpf = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuDeslogar = new javax.swing.JMenuItem();
        menuCadUsu = new javax.swing.JMenuItem();
        menuListaU = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Navegação");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("Pessoas");

        menuCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuCadastro.setText("Cadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastro);

        menuAtualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuAtualizar.setText("Atualizar Cadastro");
        menuAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAtualizarActionPerformed(evt);
            }
        });
        jMenu1.add(menuAtualizar);

        menuDeletar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuDeletar.setText("Deletar Cadastro");
        menuDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeletarActionPerformed(evt);
            }
        });
        jMenu1.add(menuDeletar);

        jMenuBar1.add(jMenu1);

        menuBusca.setText("Pesquisar");

        menuBuscaNome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuBuscaNome.setText("Buscar Nome");
        menuBuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaNomeActionPerformed(evt);
            }
        });
        menuBusca.add(menuBuscaNome);

        menuBuscaCpf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuBuscaCpf.setText("Buscar Cpf");
        menuBuscaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaCpfActionPerformed(evt);
            }
        });
        menuBusca.add(menuBuscaCpf);

        jMenuBar1.add(menuBusca);

        jMenu3.setText("Usuario");

        menuDeslogar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuDeslogar.setText("Deslogar");
        menuDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeslogarActionPerformed(evt);
            }
        });
        jMenu3.add(menuDeslogar);

        menuCadUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuCadUsu.setText("Cadastrar Usuario");
        menuCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadUsuActionPerformed(evt);
            }
        });
        jMenu3.add(menuCadUsu);

        menuListaU.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuListaU.setText("Usuarios");
        menuListaU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaUActionPerformed(evt);
            }
        });
        jMenu3.add(menuListaU);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        Cadastro cad = new Cadastro();
        cad.setVisible(true);
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void menuDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeslogarActionPerformed
        Navegacao nav = new Navegacao();
        nav.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_menuDeslogarActionPerformed

    private void menuListaUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaUActionPerformed
        ListaUsuarios listaU = new ListaUsuarios();
        listaU.setVisible(true);
    }//GEN-LAST:event_menuListaUActionPerformed

    private void menuCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadUsuActionPerformed
        CadUsuario cadU = new CadUsuario();
        cadU.setVisible(true);
    }//GEN-LAST:event_menuCadUsuActionPerformed

    private void menuAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAtualizarActionPerformed
        Atualizar att = new Atualizar();
        att.setVisible(true);
    }//GEN-LAST:event_menuAtualizarActionPerformed

    private void menuBuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscaNomeActionPerformed
        BuscarPorNome bNome = new BuscarPorNome();
        bNome.setVisible(true);
    }//GEN-LAST:event_menuBuscaNomeActionPerformed

    private void menuBuscaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscaCpfActionPerformed
        BuscarPorCpf bCpf = new BuscarPorCpf();
        bCpf.setVisible(true);
    }//GEN-LAST:event_menuBuscaCpfActionPerformed

    private void menuDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeletarActionPerformed
        Deletar dPessoa = new Deletar();
        dPessoa.setVisible(true);       
    }//GEN-LAST:event_menuDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Navegacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Navegacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Navegacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Navegacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Navegacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAtualizar;
    private javax.swing.JMenu menuBusca;
    private javax.swing.JMenuItem menuBuscaCpf;
    private javax.swing.JMenuItem menuBuscaNome;
    private javax.swing.JMenuItem menuCadUsu;
    private javax.swing.JMenuItem menuCadastro;
    private javax.swing.JMenuItem menuDeletar;
    private javax.swing.JMenuItem menuDeslogar;
    private javax.swing.JMenuItem menuListaU;
    // End of variables declaration//GEN-END:variables
}
